### ISSUE TITLE
large config in web editor causes browser to hang

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#362] opened 2020-04-24 19:14 UTC
**Describe the bug**
There seems to be some sort of file size limits for the display engine used to view the config in the system settings. The config I have is currently 415 lines long (22KB on disk). If I go the system tab I get this in firefox:

<img width="1664" alt="Screen Shot 2020-04-24 at 2 52 00 PM" src="https://user-images.githubusercontent.com/503771/80247391-f5029100-863b-11ea-97b2-c385fc29eb2d.png">

Chrome hangs for a while before it sends a popup with the same thing, Wait or kill.

Chrome shows its graphql related:

<img width="384" alt="Screen Shot 2020-04-24 at 3 13 04 PM" src="https://user-images.githubusercontent.com/503771/80248577-31cf8780-863e-11ea-91f2-203596a715ac.png">

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
Still trying to nail down exactly where the limit is hit that causes it to stall.

**Expected behavior**
The config editor shouldn't stall

**Screenshots**
inline.

**System (please complete the following information):**
 - OS: OSX 10.15.4 (Catalina), 
 - Browser Chrome v80, firefox v75
 - Version latest on github as of April 23rd 2020

**Additional context**

**Comment by pixitha** [comment] 2020-04-24 19:53
387 lines of config seems safe and normal speed.

**Comment by pixitha** [comment] 2020-04-24 21:30
Could be related to large copy and paste also, not the overall length of the file. Seems to happen if I paste a large amount of the config at one time, but load better after its been fully saved and the page totally refreshed?

**Comment by slowr** [comment] 2020-04-25 14:17
@pixitha graphql connection stays open forever as it's a websocket. Can you check on the `network` tab the times for the websocket messages?
![image](https://user-images.githubusercontent.com/3428023/80282163-32385300-8710-11ea-873b-263a2dce2cad.png)

**Comment by pixitha** [comment] 2020-04-27 16:06
<img width="1667" alt="Screen Shot 2020-04-27 at 12 01 54 PM" src="https://user-images.githubusercontent.com/503771/80394227-92013c00-887f-11ea-9ffb-d08c548a28d1.png">

**Comment by pixitha** [comment] 2020-04-27 16:29
<img width="1677" alt="Screen Shot 2020-04-27 at 12 27 53 PM" src="https://user-images.githubusercontent.com/503771/80396467-ad217b00-8882-11ea-9873-ce0ef4c1abe6.png">

**Comment by slowr** [comment] 2020-04-27 17:19
I want to see if the problem is on the yaml renderer that we use. If you can follow these steps and tell me if it runs ok. Use chrome and go to the sources tab:
![step1](https://user-images.githubusercontent.com/3428023/80400714-7ddb3000-88bb-11ea-9fb7-265dfe571b74.jpg)

Then find the `prod-graphql.js` and double-click it:
![step2](https://user-images.githubusercontent.com/3428023/80400733-829fe400-88bb-11ea-8ac8-6d66beccdea0.jpg)

Then go to line 42 and click on the number to turn blue (it should be the fetchConfigStatsLive function) and then refresh the page:
![step3](https://user-images.githubusercontent.com/3428023/80400730-816eb700-88bb-11ea-85e3-62881c93106a.jpg)

After refreshing you will hit a breakpoint there and then you need to write on the console on the bottom `b = function(){}`:
![step4](https://user-images.githubusercontent.com/3428023/80400723-7fa4f380-88bb-11ea-9e2d-741789e92198.jpg)

Finally, click again on the line 42 to remove the breakpoint and click on the resume button for the script to continue.
![step5](https://user-images.githubusercontent.com/3428023/80400720-7e73c680-88bb-11ea-9d61-00c36d0999cb.jpg)

 If the page has loaded normally (it will not show the configuration though) and fast then it means that the render of the configuration is the slow part.

**Comment by pixitha** [comment] 2020-04-27 18:04
The page still seemed to load a bit slower, but not as slow/unresponsive as when the function is left to run.

<img width="1680" alt="Screen Shot 2020-04-27 at 2 03 58 PM" src="https://user-images.githubusercontent.com/503771/80404965-f5936580-888f-11ea-824c-970ceef80947.png">

**Comment by pixitha** [comment] 2020-04-27 18:12
After testing the above the page loads quickly and I can scroll around the page normally as soon as its on screen, unlike when its hung.

**Comment by vkotronis** [comment] 2020-06-26 15:37
According to @pixitha this may be related to autoformatting. Therefore, we need to look in the code for places where we write the entire configuration in an automated way and deactivate them with a flag to check if the hanging issue is dealt with. Will make a small PR on this soon.

**Comment by vkotronis** [comment] 2021-05-13 10:42
Tentatively fixed in new frontend (to be released). Closing for now, will re-open if problem persists.

**Closed by vkotronis** 2021-05-13 10:42 UTC
Labels: autoconf, bug, frontend, p/high
