### ISSUE TITLE
verify podman support and podman-compose

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#291] opened 2019-12-27 20:39 UTC
**Is your feature request related to a problem? Please describe.**
Our software image team has moved to podman, and does not use docker anymore. Need help to test artemis with podman and podman-compose

**Describe the solution you'd like**
Need help to test artemis with podman and podman-compose

**Describe alternatives you've considered**
First attempt to run with a fresh install was un-successful, only 3 container launched. No idea which part was broken, probably my podman install.

**Additional context**
```sudo podman ps -a
CONTAINER ID  IMAGE                                               COMMAND               CREATED        STATUS                      PORTS               NAMES
6b3ddb19a6d1  docker.io/library/nginx:1.15-alpine                 nginx -g daemon o...  3 minutes ago  Exited (1) 3 minutes ago    0.0.0.0:80->80/tcp  nginx
e24f2a0e40b1  docker.io/subzerocloud/pg-amqp-bridge:0.0.6         /root/wait-for ra...  4 minutes ago  Exited (126) 4 minutes ago  0.0.0.0:80->80/tcp  pg-amqp-bridge
fc11e2c491a8  docker.io/postgrest/postgrest:v5.2.0                /bin/sh -c exec p...  4 minutes ago  Up 4 minutes ago            0.0.0.0:80->80/tcp  postgrest
9598f44b76d1  docker.io/inspiregroup/artemis-backend:latest       ./entrypoint          4 minutes ago  Up 4 minutes ago            0.0.0.0:80->80/tcp  backend
afb2f8f0e7f6  docker.io/hasura/graphql-engine:v1.0.0-alpha45      graphql-engine se...  5 minutes ago  Exited (1) 5 minutes ago    0.0.0.0:80->80/tcp  graphql
81c9d714fbe8  docker.io/inspiregroup/artemis-monitor:latest       ./entrypoint          5 minutes ago  Up 5 minutes ago            0.0.0.0:80->80/tcp  monitor
7ec234823091  docker.io/library/rabbitmq:3.7.8-management-alpine  docker-entrypoint...  5 minutes ago  Exited (0) 5 minutes ago    0.0.0.0:80->80/tcp  rabbitmq
99976e463ddf  k8s.gcr.io/pause:3.1```

**Comment by slowr** [comment] 2019-12-28 18:47
seems like our containers work correctly. the issue with the ones failing might be incopatibility issues with podman/docker. I will dig a bit more and update my findings here

**Comment by slowr** [comment] 2019-12-29 16:21
@pixitha it seems that the `podman-compose` project is very mature and has a lot of bugs or missing functionality (executing stop will trigger start instead, etc) but I got our project to work nevertheless.

The problem seems to be with the network namespacing mechanism that they are using. We have two different containers, **backend** and **monitor** that happen to use the same port for supervisor. Docker provides full network isolation so there is no problem having this. On the other hand, podman sees a port conflict so there might be an issue on how they do the network isolation between different containers!

You can bypass this issue by changing the `MON_SUPERVISOR_PORT` variable in the `.env` file to another value (i.e. `MON_SUPERVISOR_PORT=9005`) and then also changing in `monitor/supervisor.d/services.conf`:
```
 [inet_http_server]
-port = 0.0.0.0:9001
+port = 0.0.0.0:9005
```

Lastly, another small change to avoid parsing issues with podman-compose, add quotes to these variables in `docker-compose.yaml` file:
```
-            - 80 # HTTP
-            - 443 # HTTPS
+            - "80" # HTTP
+            - "443" # HTTPS
```

Can you update afterwards if these changes were enough to get your setup to work? Cheers!

**Comment by slowr** [comment] 2019-12-29 16:24
By the way, I couldn't reproduce your state of containers exiting so it might be due to another issues that you might have on your setup. Can you check the logs of the exited containers? (podman logs `name-of-container`)

**Comment by slowr** [comment] 2019-12-29 16:57
Lastly, I would like to recommend telling your team to look at this solution: https://docs.docker.com/engine/security/rootless/.

It's pretty much rootless docker and works out of the box ( only difference that you will need to change the ports from 80, 443 to something else because these ports require sudo :) )

**Comment by slowr** [comment] 2020-01-09 00:14
Closing this issue unless the author wants to add more information or if it's still unresolved.

**Closed by slowr** 2020-01-09 00:14 UTC
Labels: container, docker, p/low
